image: node:12
stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/node:$CI_COMMIT_REF_SLUG
build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
    - docker cp $(docker run --rm -d $IMAGE_TAG):/app/node_modules node_modules
    - docker cp $(docker run --rm -d $IMAGE_TAG):/app/build build
  cache:
    key: build-cache
    paths:
      - node_modules/
      - build/
test:
  stage: test
  script:
    - npm test
  cache:
    key: build-cache
pages:
  stage: deploy
  script:
    - ls
    - rm -rf public
    - mv build public
    - cp public/index.html public/404.html
  cache:
    key: build-cache
  artifacts:
    paths:
      - public
  only:
    - master
