version: '3.3'

services:
  node:
    build: .
    user: ${CURRENT_UID}
    restart: always
    command: yarn run start
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules