version: '3.3'

services:
  node:
    build:
      dockerfile: Dockerfile
      context: docker/node
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    restart: always
    command: yarn run start
    ports:
      - 3000:3000
    volumes:
      - .:/app